### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by danisenko123** [frzi/SwiftChatApp#1]
Good afternoon, 
I did a chat according to your example, 
but I can't figure out how to start two devices and check the chat

**Comment by frzi** [comment]
In Xcode you can run multiple simulators simultaneously. Select a different simulator and hit the “run” button again.

**Comment by danisenko123** [comment]
Can me look  screen

**Comment by danisenko123** [comment]
Can you send me a screenshot of how to do this I'm new to Xcode

**Comment by danisenko123** [comment]
eyNotFound(CodingKeys(stringValue: "message", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"message\", intValue: nil) (\"message\").", underlyingError: nil)) 
And I have such an error when sending messages.

**Comment by frzi** [comment]
> Can you send me a screenshot of how to do this I'm new to Xcode

In Xcode, next to the target name, click the device/simulator:
<img width="389" alt="Schermafbeelding 2021-01-17 om 13 52 55" src="https://user-images.githubusercontent.com/8537579/104843530-6b7ea780-58cb-11eb-9180-eff9a4d34de0.png">
Then select a different simulator:
<img width="485" alt="Schermafbeelding 2021-01-17 om 13 51 53" src="https://user-images.githubusercontent.com/8537579/104843538-746f7900-58cb-11eb-975e-1d48f3f3a987.png">

You can do this several times to run multiple instances of the iOS simulator (careful though, this can require a bit of CPU and memory!)


> eyNotFound(CodingKeys(stringValue: "message", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: "message", intValue: nil) ("message").", underlyingError: nil))
> And I have such an error when sending messages.

Make sure the `SubmittedChatMessage` model is exactly the same in both the app project and in the server project. These have to be identical.


If you're unsure what is wrong with your code you can clone this repository and compare it with your own.
